import React,{useState} from 'react'
import {
    View,
    Text,
    TextInput,
    TouchableOpacity,
    ActivityIndicator,
    ScrollView,
    Image

} from 'react-native';
import { ForgetpasswordStyle } from './ForgetpasswordStyle';
import LinearGradient from 'react-native-linear-gradient';
import FontAwesome from 'react-native-vector-icons/FontAwesome';
import { useDispatch } from 'react-redux';
import { forgetpassword } from '../../store/actions/AuthAction';
import { useSelector } from "react-redux";
import AppConfigColors from '../../config/AppConfig'



export default function Forgetpassword({navigation}) {
    const [Colors]= AppConfigColors()
    const [invalidemail, setinvalidemail] = useState()
       const invalid= useSelector(state => state.AuthReducer.wrongemail);
       const [loading, setloading] = useState(false)
       
const [useremail, setuseremail] = useState('')
const [message, setmessage] = useState('')
const dispatch = useDispatch()

    const forget=()=>{
        setmessage('')
        if (useremail !== '') {
            dispatch(forgetpassword(setloading,useremail));
        }else{
             setmessage('Please enter your email first')
        }
       
    }
    return (
        <ScrollView
        showsVerticalScrollIndicator ={false}
        showsHorizontalScrollIndicator={false}
         style={[ForgetpasswordStyle.root,{backgroundColor: Colors.Primary,}]}
         >
            <View style={ForgetpasswordStyle.logo_container}>
                <TouchableOpacity onPress={()=>navigation.goBack()} style={{position:'absolute',top:10,alignSelf:'flex-start',paddingHorizontal:30}}>
                    <Image style={{tintColor:Colors.textColor,height:40,width:40,resizeMode:'contain'}} source={require('../../assets/back.png')} />
                </TouchableOpacity>
                <Text style={ForgetpasswordStyle.textheader}>Forget Password</Text>
            </View>
            <View style={ForgetpasswordStyle.input_container}>
                {/* <Text>If You Want To Recover Your Password These Are Some Step Here .First You Have To Write Your Correct Email And Click On Forget Password Button Soon You Will Get An Message On Your Email Inbox And There You Will Receive Your New Password .The Password Is Generated By Auto Server </Text> */}
                <Text style={ForgetpasswordStyle.input_lable}>Email</Text>
                <View style={ForgetpasswordStyle.action}>
                    <FontAwesome
                        name="user-o"
                        color="gray"
                        size={20}
                    />
                    <TextInput
                        placeholder="Enter Your Email"
                        placeholderTextColor="#666666"
                        style={ForgetpasswordStyle.textInput}
                        autoCapitalize="none"
                        onChangeText={text=>setuseremail(text)}
                    />
                   
                </View>
                <Text style={{color:'#FF6666'}}>{invalid}</Text>
                <Text style={{color:'#FF6666'}}>{message}</Text>
                {loading ?
                 <View style={[ForgetpasswordStyle.signIn, {

                    marginTop: '50%'
                    }]}>
                        <LinearGradient
                    colors={[Colors.Primary, Colors.Primary]}
                    style={ForgetpasswordStyle.signIn}
                >
                        <ActivityIndicator  size="small" color="white"/>
                        </LinearGradient>
                    </View>
                :
                <TouchableOpacity
                onPress={forget}
                  style={[ForgetpasswordStyle.signIn, {

                      marginTop: '30%'
                  }]}
              ><LinearGradient
                  colors={[Colors.Primary, Colors.Primary]}
                  style={ForgetpasswordStyle.signIn}
              >
                      <Text style={[ForgetpasswordStyle.textSign,{color:Colors.textColor}]}
                      >Forget Password</Text>
                  </LinearGradient>
              </TouchableOpacity>
                }

                
            </View>
        </ScrollView>
    )
}
